### ISSUE TITLE
cannot load such file -- octopress-genesis-theme (LoadError)

### ISSUE THREAD

**Issue by maiertech** [octopress/genesis-theme#6]
I'm trying to add the theme to a Jekyll project, but I get the following error. Anyone knows what's causing this?

```
Configuration file: /home/ubuntu/workspace/_config.yml
/usr/local/rvm/gems/ruby-2.1.1@rails4/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:28:in `require': cannot load such file -- octopress-genesis-theme (LoadError)
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:28:in `block in require_gems'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:26:in `each'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:26:in `require_gems'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/jekyll-2.4.0/lib/jekyll/site.rb:74:in `setup'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/jekyll-2.4.0/lib/jekyll/site.rb:36:in `initialize'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:28:in `new'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:28:in `process'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:17:in `block (2 levels) in init_with_program'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `call'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `each'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `execute'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/mercenary-0.3.4/lib/mercenary/program.rb:35:in `go'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/mercenary-0.3.4/lib/mercenary.rb:22:in `program'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/bin/jekyll:23:in `load'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/bin/jekyll:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.1.1@rails4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mandreko** [comment]
I just ran across this today, and the solution from @mdotasia worked for me as well.

**Comment by imathis** [comment]
Ah yes, I need to push out another release with these fixes. Thanks for the ping. :)

**Comment by tristil** [comment]
@imathis Another ping :) 

As an aside, in the various READMEs it's ambiguous whether you just need to include the gem in `jekyll_plugins` group or you need to also include it in the gems list as well. Many plugins seem to not need it but this theme seemed to need it.

**Comment by kim0** [comment]
Is this really not solved yet .. or am I doing something wrong?
