### ISSUE TITLE
add the gem to your Jekyll configuration

### ISSUE THREAD

**Issue by change2hao** [octopress/genesis-theme#9]
when I add the gem to my Jekyll configuration,and running ```jekyll build```
the console show errror: ```Configuration file: /Users/tianliwei/blog/_config.yml
jekyll 2.5.3 | Error:  undefined method `each' for "-octopress-genesis-theme":String```

**Comment by imathis** [comment]
Thanks for the report. This is very much still a work in progress.

**Comment by parkr** [comment]
@change2hao Make sure your gem declaration in `_config.yml` is an array:

```yml
gems: [octopress-genesis-theme]
```

or simply

```yml
gems:
- octopress-genesis-theme
```

If that doesn't fix it, please re-run `jekyll build --trace` and paste the output.

**Comment by change2hao** [comment]
@parkr 
I declaration 
```
gems:
  -octopress-genesis-theme
```
and follow your advice, i changed to
```
gems:
- octopress-genesis-theme
```
and the trace as follows:
```
Configuration file: /Users/tianliwei/blog/_config.yml
/Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- octopress-genesis-theme (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'
```
and i have installed octopress-genesis-theme use ```gem install octopress-genesis-theme```

**Comment by ludwick** [comment]
The rb file in the installed gem is actually just octopress-genesis.rb in my installation:

```
find /Users/rachael/.rvm/gems/ruby-2.2.0/gems/octopress-genesis-theme-0.0.3/lib
/Users/rachael/.rvm/gems/ruby-2.2.0/gems/octopress-genesis-theme-0.0.3/lib
/Users/rachael/.rvm/gems/ruby-2.2.0/gems/octopress-genesis-theme-0.0.3/lib/octopress-genesis
/Users/rachael/.rvm/gems/ruby-2.2.0/gems/octopress-genesis-theme-0.0.3/lib/octopress-genesis/category-generator.rb
/Users/rachael/.rvm/gems/ruby-2.2.0/gems/octopress-genesis-theme-0.0.3/lib/octopress-genesis/version.rb
/Users/rachael/.rvm/gems/ruby-2.2.0/gems/octopress-genesis-theme-0.0.3/lib/octopress-genesis.rb
```

If I change _config.yaml to mention:
```
gems: [octopress-genesis]
````
It gets passed this.

**Comment by ludwick** [comment]
But, if I just use latest in github (see [here](https://github.com/octopress/genesis-theme/issues/6#issuecomment-63200915) for how) then it has the right name.

**Comment by imathis** [comment]
It's octopress-genesis-theme. I've updated the readme. Thanks.
